version: '3.3'

services:
  db:
    image: postgres:9.6.24
    restart: always
    environment:
      - POSTGRES_DB=example
      - POSTGRES_PASSWORD=teste123
    ports:
      - '5432:5432'
    expose:
      - 5432

    volumes:
      - my-db:/var/lib/postgres

  rabbit:
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=pass
    ports:
      - '5673:5672'
      - '15673:15672'
    expose:
      - 15673
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/
      - rabbitmq_log:/var/log/rabbitmq/
    networks:
      - rabbitmq_go_net

networks:
  rabbitmq_go_net:
    driver: bridge

volumes:
  my-db:
  rabbitmq_data:
  rabbitmq_log: